name: Package proxsuite
on:
  repository_dispatch:
    types:
    - package-master
  pull_request:
    branches:
    - "**"
  push:
    branches:
    - debian
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      main-branch: debian
      update-stable-and-head: true
      deps: '["isri-aist/QpSolverCollection"]'
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
